#!/bin/bash

#You can either add your puush-api-key as an enviroment Variable (look at readme) or add it directly to the script, by uncommenting the next Line
#PUUSH_API_KEY="YOUR-KEY-HERE"

#Exit on error
set -e

# Set sensible defaults for Variables
[ -z "$SCREENSHOT_DIR" ] &&	SCREENSHOT_DIR="$HOME/Pictures/"
[ -z "$DIR" ] && SCREENSHOT_FILE="ss_$(date "+%s").png"
SCREENSHOT_PATH="$SCREENSHOT_DIR$SCREENSHOT_FILE"
[ -z "$SCREENSHOT_COMMAND" ] &&	SCREENSHOT_COMMAND="scrot $* $SCREENSHOT_PATH"

if [ -z "$PUUSH_API_KEY" ] ; then
	echo "puush-screenshot error: Variable PUUSH_API_KEY is not defined. Please add it as an enviroment variable or to the script" 1>&2
	exit 2
fi

$SCREENSHOT_COMMAND
OUT=$(curl "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=poop" -F "f=@$SCREENSHOT_PATH" | sed -E 's/^.+,(.+),.+,.+$/\1\n/')
if [ "$OUT" == "-1," ]; then
	echo "puush-screenshot error: Couldn't upload screenshot, Invalid API Key" 1>&2
	exit 2
else
	echo $OUT | xclip -sel clip
	notify-send "Link was copied to your Clipboard"
	exit 0
fi